import { useState } from 'react';
import { HelpCircle, ChevronDown, ChevronUp, ArrowDownLeft, ArrowUpRight, Shield, Zap, Users, Lock, AlertTriangle, CheckCircle, Settings, Star, MessageCircle } from 'lucide-react';

const SECTIONS = [
  { id: 'deposit',     label: 'How to Deposit',      icon: ArrowDownLeft, color: 'var(--green)' },
  { id: 'withdraw',    label: 'How to Withdraw',     icon: ArrowUpRight,  color: 'var(--red)' },
  { id: 'bot',         label: 'Quant Engine',        icon: Zap,           color: 'var(--yellow)' },
  { id: 'vip',         label: 'VIP Tiers',           icon: Star,          color: 'var(--purple2)' },
  { id: 'account',     label: 'Account Settings',    icon: Settings,      color: 'var(--cyan)' },
  { id: 'referrals',   label: 'Referral Program',    icon: Users,         color: 'var(--green)' },
  { id: 'security',    label: 'Security',            icon: Lock,          color: 'var(--yellow)' },
  { id: 'regulations', label: 'Terms & Regulations', icon: Shield,        color: 'var(--text2)' },
  { id: 'faq',         label: 'FAQ',                 icon: HelpCircle,    color: 'var(--brand-1)' },
];

const VIP_TIERS = [
  { name: 'Starter',  min: '$100',    rate: '1.80', color: '#6b7280' },
  { name: 'Silver',   min: '$500',    rate: '2.20', color: '#94a3b8' },
  { name: 'Gold',     min: '$2,000',  rate: '2.80', color: 'var(--yellow)' },
  { name: 'Platinum', min: '$5,000',  rate: '3.50', color: 'var(--cyan)' },
  { name: 'Diamond',  min: '$10,000', rate: '5.00', color: 'var(--purple2)' },
];

const FAQ_ITEMS = [
  { q: 'When does my yield get credited?', a: 'Yield is credited automatically when you stop the Quant Engine. The longer the engine runs, the more yield accumulates in real time.' },
  { q: 'Can I run the bot multiple times per day?', a: 'Each account is limited to one bot session per calendar day (UTC). Once you stop the engine, you cannot restart it until the next day.' },
  { q: 'How is my VIP tier determined?', a: 'Your VIP tier is automatically assigned based on your current account balance. It updates instantly when your balance crosses a tier threshold.' },
  { q: 'Is there a minimum withdrawal amount?', a: 'Yes. You must have a minimum balance of $100 before you can make any withdrawal. This ensures your account meets the Starter VIP tier requirement.' },
  { q: 'How long do withdrawals take?', a: 'Withdrawals are processed manually by our team within 24–72 hours. You will receive your funds to the crypto address registered on your account.' },
  { q: 'Can I change my crypto withdrawal address?', a: 'Yes. Go to Account → Crypto Address and update your wallet address and network. Changes take effect immediately for future withdrawals.' },
  { q: 'What is the referral commission rate?', a: 'You earn 5% of the yield generated by each user you refer. Commission is paid automatically when your referral stops their bot session.' },
  { q: 'What cryptocurrencies are accepted?', a: 'Nyx accepts USDT (TRC-20 and ERC-20), BTC, and ETH. Always verify the network before sending — sending on the wrong network may result in permanent loss of funds.' },
  { q: 'How do I set a transaction password?', a: 'Go to Account → Transaction Password. This secondary password is required to confirm all withdrawals, adding an extra layer of security.' },
  { q: 'Is my deposit insured?', a: 'Nyx is a yield generation platform. As with all yield platforms, returns are not guaranteed and past performance does not indicate future results. Only invest what you can afford to lose.' },
];

function Step({ n, title, desc }: { n: number; title: string; desc: string }) {
  return (
    <div className="flex gap-3">
      <div className="w-6 h-6 rounded-full flex items-center justify-center text-xs font-black flex-shrink-0 mt-0.5"
        style={{ background: 'var(--brand-1)', color: '#fff' }}>{n}</div>
      <div>
        <p className="text-xs font-semibold text-white">{title}</p>
        <p className="text-xs mt-0.5 leading-relaxed" style={{ color: 'var(--text2)' }}>{desc}</p>
      </div>
    </div>
  );
}

function Bullet({ text, color = 'var(--green)' }: { text: string; color?: string }) {
  return (
    <div className="flex items-start gap-2.5 text-xs" style={{ color: 'var(--text2)' }}>
      <div className="w-1 h-1 rounded-full mt-1.5 flex-shrink-0" style={{ background: color }} />
      <span>{text}</span>
    </div>
  );
}

function Warn({ text }: { text: string }) {
  return (
    <div className="flex items-start gap-2.5 px-3 py-2.5 rounded-lg text-xs"
      style={{ background: 'rgba(244,63,94,0.06)', border: '1px solid rgba(244,63,94,0.2)', color: 'var(--red)' }}>
      <AlertTriangle size={12} className="flex-shrink-0 mt-0.5" />
      <span>{text}</span>
    </div>
  );
}

function Good({ text }: { text: string }) {
  return (
    <div className="flex items-start gap-2.5 px-3 py-2.5 rounded-lg text-xs"
      style={{ background: 'rgba(16,185,129,0.06)', border: '1px solid rgba(16,185,129,0.18)', color: 'var(--green)' }}>
      <CheckCircle size={12} className="flex-shrink-0 mt-0.5" />
      <span>{text}</span>
    </div>
  );
}

function Card({ title, color, children }: { title: string; color: string; children: React.ReactNode }) {
  return (
    <div className="ex-card overflow-hidden">
      <div className="px-4 py-3 flex items-center gap-2"
        style={{ borderBottom: '1px solid var(--border)', borderLeft: `3px solid ${color}` }}>
        <span className="text-xs font-bold text-white">{title}</span>
      </div>
      <div className="p-4 space-y-3">{children}</div>
    </div>
  );
}

function Accordion() {
  const [open, setOpen] = useState<number | null>(null);
  return (
    <div className="space-y-1.5">
      {FAQ_ITEMS.map((item, i) => (
        <div key={i} className="ex-card overflow-hidden">
          <button className="w-full flex items-center justify-between px-4 py-3.5 text-left"
            onClick={() => setOpen(open === i ? null : i)}
            style={{ background: open === i ? 'rgba(255,255,255,0.02)' : 'transparent' }}>
            <span className="text-xs font-semibold text-white pr-4">{item.q}</span>
            {open === i
              ? <ChevronUp size={13} style={{ color: 'var(--brand-1)', flexShrink: 0 }} />
              : <ChevronDown size={13} style={{ color: 'var(--text3)', flexShrink: 0 }} />}
          </button>
          {open === i && (
            <div className="px-4 pb-4" style={{ borderTop: '1px solid var(--border)' }}>
              <p className="text-xs leading-relaxed mt-3" style={{ color: 'var(--text2)' }}>{item.a}</p>
            </div>
          )}
        </div>
      ))}
    </div>
  );
}

export default function Help() {
  const [active, setActive] = useState('deposit');
  const cur = SECTIONS.find(s => s.id === active)!;
  const CurIcon = cur.icon;

  return (
    <div className="fade-in flex flex-col lg:flex-row" style={{ minHeight: 'calc(100vh - 60px)', background: 'var(--bg)' }}>

      {/* Mobile: horizontal scrollable tab strip */}
      <div className="lg:hidden flex overflow-x-auto gap-1 p-3 flex-shrink-0"
        style={{ background: 'var(--bg-card)', borderBottom: '1px solid var(--border)' }}>
        {SECTIONS.map(s => {
          const Icon = s.icon;
          const on = active === s.id;
          return (
            <button key={s.id} onClick={() => setActive(s.id)}
              className="flex items-center gap-1.5 px-3 py-2 rounded-xl flex-shrink-0 text-left transition-all"
              style={on
                ? { background: 'rgba(99,102,241,0.12)', border: '1px solid rgba(99,102,241,0.3)', color: 'var(--text)' }
                : { background: 'var(--bg3)', border: '1px solid var(--border)', color: 'var(--text3)' }}>
              <Icon size={11} style={{ color: on ? s.color : 'var(--text3)' }} />
              <span className="text-[11px] font-medium whitespace-nowrap">{s.label}</span>
            </button>
          );
        })}
      </div>

      {/* Desktop: left nav panel */}
      <div className="hidden lg:flex flex-col flex-shrink-0 py-3" style={{
        width: 220,
        background: 'var(--bg-card)',
        borderRight: '1px solid var(--border)',
        overflowY: 'auto',
      }}>
        <p className="section-label px-4 mb-2">Help Topics</p>
        {SECTIONS.map(s => {
          const Icon = s.icon;
          const on = active === s.id;
          return (
            <button key={s.id} onClick={() => setActive(s.id)}
              className="w-full flex items-center gap-2.5 px-4 py-2.5 text-left transition-all"
              style={on
                ? { color: 'var(--text)', background: 'rgba(99,102,241,0.07)', borderLeft: '2px solid var(--brand-1)', paddingLeft: 14 }
                : { color: 'var(--text3)', borderLeft: '2px solid transparent' }}>
              <Icon size={13} style={{ color: on ? s.color : 'var(--text3)', flexShrink: 0 }} />
              <span className="text-xs font-medium" style={{ color: on ? 'var(--text)' : 'var(--text2)' }}>{s.label}</span>
            </button>
          );
        })}
        <div className="mx-3 mt-4 p-3 rounded-xl" style={{ background: 'var(--bg3)', border: '1px solid var(--border)' }}>
          <div className="flex items-center gap-2 mb-2">
            <MessageCircle size={12} style={{ color: 'var(--brand-1)' }} />
            <p className="text-[11px] font-bold text-white">Need help?</p>
          </div>
          <p className="text-[10px] leading-snug" style={{ color: 'var(--text3)' }}>Contact our support team for account-specific issues.</p>
        </div>
      </div>

      {/* Content area */}
      <div className="flex-1 overflow-y-auto">
        <div className="p-4 space-y-4 max-w-3xl">

          {/* Section header */}
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-xl flex items-center justify-center flex-shrink-0"
              style={{ background: 'var(--bg3)', border: '1px solid var(--border)' }}>
              <CurIcon size={14} style={{ color: cur.color }} />
            </div>
            <div>
              <h2 className="text-sm font-bold text-white">{cur.label}</h2>
              <p className="text-[10px]" style={{ color: 'var(--text3)' }}>NYX Platform · Help Center</p>
            </div>
          </div>

          {active === 'deposit' && <>
            <Card title="How to Make a Deposit" color="var(--green)">
              <Step n={1} title="Go to Assets" desc="Click 'Assets' in the left sidebar." />
              <Step n={2} title="Click Deposit" desc="Press the green Deposit button at the top of the page." />
              <Step n={3} title="Enter Amount" desc="Type the amount you wish to deposit. Minimum is $50." />
              <Step n={4} title="Confirm" desc="Click Confirm Deposit. Your balance updates immediately." />
            </Card>
            <Card title="Deposit Requirements & Limits" color="var(--green)">
              <Bullet text="Minimum deposit: $50" />
              <Bullet text="To activate the Quant Engine, balance must be ≥ $100" />
              <Bullet text="To unlock withdrawals, balance must reach $100" />
              <Bullet text="No maximum deposit limit" />
              <Bullet text="Deposits are credited instantly" />
            </Card>
            <Card title="Accepted Cryptocurrencies" color="var(--green)">
              <Bullet text="USDT — TRC-20 (Tron network)" />
              <Bullet text="USDT — ERC-20 (Ethereum network)" />
              <Bullet text="BTC — Bitcoin network" />
              <Bullet text="ETH — Ethereum network" />
              <Warn text="Always verify the network before sending. Funds sent on the wrong network cannot be recovered." />
              <Good text="Contact support if your deposit does not appear within 30 minutes of blockchain confirmation." />
            </Card>
          </>}

          {active === 'withdraw' && <>
            <Card title="How to Make a Withdrawal" color="var(--red)">
              <Step n={1} title="Set Your Crypto Address" desc="Go to Account → Crypto Address and save your wallet address and network." />
              <Step n={2} title="Set a Transaction Password" desc="Go to Account → Transaction Password. Required for all withdrawals." />
              <Step n={3} title="Go to Assets" desc="Click 'Assets' in the sidebar." />
              <Step n={4} title="Click Withdraw" desc="The Withdraw button is enabled once your balance is ≥ $100." />
              <Step n={5} title="Enter Amount & Password" desc="Enter the withdrawal amount and your transaction password to confirm." />
              <Step n={6} title="Wait for Processing" desc="Withdrawals are processed manually within 24–72 hours to your registered address." />
            </Card>
            <Card title="Withdrawal Requirements" color="var(--red)">
              <Bullet text="Minimum balance to withdraw: $100" color="var(--red)" />
              <Bullet text="A registered crypto address is required" color="var(--red)" />
              <Bullet text="A transaction password must be set" color="var(--red)" />
              <Bullet text="Minimum withdrawal amount: $10" color="var(--red)" />
              <Bullet text="Processing time: 24–72 hours" color="var(--red)" />
              <Warn text="Ensure your crypto address and network are correct. Nyx is not responsible for funds sent to incorrect addresses." />
            </Card>
            <Card title="Withdrawal Limits by VIP Tier" color="var(--red)">
              <div className="overflow-x-auto">
                <table className="w-full text-xs">
                  <thead><tr style={{ borderBottom: '1px solid var(--border)' }}>
                    {['Tier','Min Withdrawal','Daily Limit','Processing'].map(h => (
                      <th key={h} className="py-2 text-left pr-6 text-[10px] font-bold uppercase tracking-wide" style={{ color: 'var(--text3)' }}>{h}</th>
                    ))}
                  </tr></thead>
                  <tbody>
                    {[
                      { t: 'Starter',  c: '#6b7280',           d: '$500',     p: '48–72h' },
                      { t: 'Silver',   c: '#94a3b8',           d: '$2,000',   p: '24–48h' },
                      { t: 'Gold',     c: 'var(--yellow)',      d: '$5,000',   p: '24h' },
                      { t: 'Platinum', c: 'var(--cyan)',        d: '$15,000',  p: '12–24h' },
                      { t: 'Diamond',  c: 'var(--purple2)',     d: 'Unlimited',p: '12h' },
                    ].map(r => (
                      <tr key={r.t} style={{ borderBottom: '1px solid var(--border)' }}
                        onMouseEnter={e => (e.currentTarget.style.background = 'rgba(255,255,255,0.015)')}
                        onMouseLeave={e => (e.currentTarget.style.background = 'transparent')}>
                        <td className="py-2.5 pr-6 font-bold text-xs" style={{ color: r.c }}>{r.t}</td>
                        <td className="py-2.5 pr-6 mono text-xs" style={{ color: 'var(--text2)' }}>$10</td>
                        <td className="py-2.5 pr-6 mono text-xs font-semibold" style={{ color: 'var(--green)' }}>{r.d}</td>
                        <td className="py-2.5 pr-6 text-xs" style={{ color: 'var(--text3)' }}>{r.p}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </Card>
          </>}

          {active === 'bot' && <>
            <Card title="How the Quant Engine Works" color="var(--yellow)">
              <Step n={1} title="Deposit at least $100" desc="Your balance must be ≥ $100 to activate the engine (Starter VIP tier)." />
              <Step n={2} title="Go to Quant Engine" desc="Click 'Quant Engine' in the sidebar." />
              <Step n={3} title="Start the Engine" desc="Click START. Yield begins accumulating immediately at your VIP tier rate." />
              <Step n={4} title="Watch it Earn" desc="The live chart and terminal log show earnings accumulating in real time." />
              <Step n={5} title="Stop & Collect" desc="Click STOP. Your yield is instantly added to your balance." />
            </Card>
            <Card title="Engine Rules & Limits" color="var(--yellow)">
              <Bullet text="One session per day — resets at midnight UTC" color="var(--yellow)" />
              <Bullet text="Minimum balance to start: $100" color="var(--yellow)" />
              <Bullet text="Yield rate is locked at your VIP tier when you press START" color="var(--yellow)" />
              <Bullet text="Yield accumulates continuously while the engine is running" color="var(--yellow)" />
              <Good text="To maximize earnings, deposit enough to reach the next VIP tier before starting the engine." />
            </Card>
          </>}

          {active === 'vip' && <>
            <Card title="VIP Tier Table" color="var(--purple2)">
              <div className="overflow-x-auto">
                <table className="w-full text-xs">
                  <thead><tr style={{ borderBottom: '1px solid var(--border)' }}>
                    {['Tier','Min Balance','Daily Rate','Est. Monthly'].map(h => (
                      <th key={h} className="py-2 text-left pr-6 text-[10px] font-bold uppercase tracking-wide" style={{ color: 'var(--text3)' }}>{h}</th>
                    ))}
                  </tr></thead>
                  <tbody>
                    {VIP_TIERS.map(t => (
                      <tr key={t.name} style={{ borderBottom: '1px solid var(--border)' }}
                        onMouseEnter={e => (e.currentTarget.style.background = 'rgba(255,255,255,0.015)')}
                        onMouseLeave={e => (e.currentTarget.style.background = 'transparent')}>
                        <td className="py-3 pr-6 text-xs font-bold" style={{ color: t.color }}>{t.name}</td>
                        <td className="py-3 pr-6 mono text-xs" style={{ color: 'var(--text2)' }}>{t.min}</td>
                        <td className="py-3 pr-6 mono text-xs font-bold" style={{ color: 'var(--green)' }}>{t.rate}%/day</td>
                        <td className="py-3 pr-6 mono text-xs" style={{ color: 'var(--yellow)' }}>~{(parseFloat(t.rate) * 30).toFixed(0)}%</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </Card>
            <Card title="How Tiers Work" color="var(--purple2)">
              <Bullet text="Tier is automatically assigned based on your current balance" color="var(--purple2)" />
              <Bullet text="Upgrades and downgrades happen instantly" color="var(--purple2)" />
              <Bullet text="Rate applied is the one active when you START the engine" color="var(--purple2)" />
              <Good text="Deposit more before starting to lock in a higher tier rate for that session." />
            </Card>
          </>}

          {active === 'account' && <>
            <Card title="Update Profile" color="var(--cyan)">
              <Step n={1} title="Go to Settings" desc="Click 'Settings' in the left sidebar." />
              <Step n={2} title="Edit & Save" desc="Update your full name and click Save." />
            </Card>
            <Card title="Set Crypto Withdrawal Address" color="var(--cyan)">
              <Step n={1} title="Settings → Crypto Address" desc="Scroll to the Crypto Address section." />
              <Step n={2} title="Enter Wallet Address" desc="Paste your full wallet address." />
              <Step n={3} title="Select Network" desc="Choose the correct network (TRC-20, ERC-20, BTC, ETH)." />
              <Step n={4} title="Save" desc="Click Save Address. Used for all future withdrawals." />
              <Warn text="Double-check address and network before saving. Funds sent to wrong addresses cannot be recovered." />
            </Card>
            <Card title="Set Transaction Password" color="var(--cyan)">
              <Step n={1} title="Settings → Transaction Password" desc="Scroll to the Transaction Password section." />
              <Step n={2} title="Enter & Confirm" desc="Choose a secure password different from your login password." />
              <Step n={3} title="Save" desc="Click Set Password." />
              <Good text="Transaction password is required for every withdrawal. Keep it safe — it cannot be recovered if lost." />
            </Card>
            <Card title="Change Login Password" color="var(--cyan)">
              <Step n={1} title="Settings → Change Password" desc="Scroll to the Change Password section." />
              <Step n={2} title="Enter Current Password" desc="Provide your existing login password for verification." />
              <Step n={3} title="Enter New Password" desc="Enter and confirm your new password (min. 6 characters)." />
              <Step n={4} title="Save" desc="Click Update Password." />
            </Card>
          </>}

          {active === 'referrals' && <>
            <Card title="How the Referral Program Works" color="var(--green)">
              <Step n={1} title="Find Your Code" desc="Go to the Referrals page. Your unique code and shareable link are at the top." />
              <Step n={2} title="Share Your Link" desc="Copy and share your referral link with friends or on social media." />
              <Step n={3} title="Friend Registers" desc="When someone registers using your code, they are linked to your account." />
              <Step n={4} title="Earn Commission" desc="Every time your referral runs and stops the engine, you earn 5% of their yield automatically." />
            </Card>
            <Card title="Referral Rules" color="var(--green)">
              <Bullet text="Commission rate: 5% of referral's yield per session" />
              <Bullet text="Commission is paid instantly when referral stops their engine" />
              <Bullet text="No limit on number of referrals" />
              <Bullet text="Referral code can only be applied at registration — cannot be added later" />
              <Warn text="Self-referral is not permitted and will result in account suspension." />
            </Card>
          </>}

          {active === 'security' && <>
            <Card title="Account Security Best Practices" color="var(--yellow)">
              <Bullet text="Use a strong, unique password for your Nyx account" color="var(--yellow)" />
              <Bullet text="Set a transaction password different from your login password" color="var(--yellow)" />
              <Bullet text="Never share your credentials or transaction password with anyone" color="var(--yellow)" />
              <Bullet text="Always verify your crypto address before saving" color="var(--yellow)" />
              <Bullet text="Log out from shared or public devices after use" color="var(--yellow)" />
              <Bullet text="Nyx staff will never ask for your password" color="var(--yellow)" />
            </Card>
            <Card title="Two-Layer Security" color="var(--yellow)">
              <Bullet text="Login password — protects access to your account" color="var(--yellow)" />
              <Bullet text="Transaction password — required to confirm all withdrawals" color="var(--yellow)" />
              <Warn text="If you suspect unauthorized access, change your password immediately and contact support." />
            </Card>
          </>}

          {active === 'regulations' && <>
            <Card title="Terms of Service" color="var(--text2)">
              <Bullet text="You must be at least 18 years of age to use this platform." color="var(--text2)" />
              <Bullet text="You are responsible for the security of your account credentials." color="var(--text2)" />
              <Bullet text="You agree not to use the platform for any illegal activities including money laundering or fraud." color="var(--text2)" />
              <Bullet text="Nyx reserves the right to suspend or terminate accounts that violate these terms." color="var(--text2)" />
              <Bullet text="All transactions are final once processed." color="var(--text2)" />
              <Bullet text="Nyx may update these terms at any time. Continued use constitutes acceptance." color="var(--text2)" />
            </Card>
            <Card title="Risk Disclosure" color="var(--red)">
              <Warn text="Cryptocurrency and yield platforms carry significant financial risk. Only invest what you can afford to lose." />
              <Bullet text="Past yield performance does not guarantee future results." color="var(--red)" />
              <Bullet text="Cryptocurrency values are highly volatile and can decrease rapidly." color="var(--red)" />
              <Bullet text="Nyx does not provide financial advice. All investment decisions are your own." color="var(--red)" />
              <Bullet text="Yield rates may change based on market conditions." color="var(--red)" />
            </Card>
            <Card title="Privacy Policy" color="var(--text2)">
              <Bullet text="We collect only the data necessary to operate your account (name, email, wallet address)." color="var(--text2)" />
              <Bullet text="Your data is never sold to third parties." color="var(--text2)" />
              <Bullet text="All data is stored securely and encrypted at rest." color="var(--text2)" />
              <Bullet text="You may request deletion of your account and data at any time by contacting support." color="var(--text2)" />
            </Card>
          </>}

          {active === 'faq' && <Accordion />}
        </div>
      </div>
    </div>
  );
}

